// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Scanner.flex

/* JFlex specification for FlowLang Lexical Analyzer */


@SuppressWarnings("fallthrough")
public class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING_STATE = 2;
  public static final int CHAR_STATE = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\1\0\1\10\1\11\1\12\2\13\1\14"+
    "\1\15\1\13\1\16\1\17\1\20\12\21\2\13\1\22"+
    "\1\23\1\22\2\0\4\24\1\25\25\24\1\13\1\26"+
    "\1\13\1\0\1\27\1\0\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\27\1\36\1\37\1\27\1\40\1\41"+
    "\1\27\1\42\1\43\1\44\1\27\1\45\1\46\1\47"+
    "\1\50\5\27\1\13\1\51\1\13\7\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\1\1\5\1\1"+
    "\1\6\1\7\4\5\1\10\1\11\1\12\1\13\14\14"+
    "\1\1\1\15\1\16\1\17\1\0\1\15\1\20\1\0"+
    "\1\21\1\15\1\11\1\22\1\23\1\3\1\12\1\24"+
    "\1\25\1\13\15\14\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\2\35\1\23\1\36\1\13\14\14\1\37"+
    "\1\36\1\0\1\13\4\14\1\40\4\14\1\41\1\36"+
    "\1\0\1\36\1\13\5\14\1\36\1\13\2\14\1\36"+
    "\1\13\1\36\1\13\1\42\27\13";

  private static int [] zzUnpackAction() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\176\0\374"+
    "\0\176\0\u0126\0\176\0\176\0\u0150\0\u017a\0\u01a4\0\u01ce"+
    "\0\u01f8\0\322\0\322\0\u0222\0\u024c\0\u0276\0\u02a0\0\u02ca"+
    "\0\u02f4\0\u031e\0\u0348\0\u0372\0\u039c\0\u03c6\0\u03f0\0\u041a"+
    "\0\u0444\0\u046e\0\176\0\176\0\u0498\0\u04c2\0\176\0\u04c2"+
    "\0\176\0\u04ec\0\176\0\u0516\0\u0540\0\176\0\176\0\176"+
    "\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612\0\u063c\0\u0666\0\u0690"+
    "\0\u06ba\0\u06e4\0\u070e\0\u0738\0\u0762\0\u078c\0\u07b6\0\176"+
    "\0\176\0\176\0\176\0\176\0\176\0\176\0\176\0\u04c2"+
    "\0\u07e0\0\u080a\0\u0834\0\u085e\0\u0888\0\u08b2\0\u08dc\0\u0906"+
    "\0\u0930\0\u095a\0\u0984\0\u09ae\0\u09d8\0\u0a02\0\u0a2c\0\176"+
    "\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28\0\u0b52\0\u024c"+
    "\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa\0\u024c\0\u0c24\0\u0c4e\0\u0c4e"+
    "\0\u0c78\0\u0ca2\0\u0ccc\0\u0cf6\0\u0d20\0\u0d4a\0\u0d74\0\u0d9e"+
    "\0\u0dc8\0\u0df2\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a\0\u0ec4\0\u0eee"+
    "\0\u0f18\0\u0f42\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\u1014\0\u103e"+
    "\0\u1068\0\u1092\0\u10bc\0\u10e6\0\u1110\0\u113a\0\u1164\0\u118e"+
    "\0\u11b8\0\u11e2\0\u120c\0\u1236\0\u1260\0\176";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\0\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\4\1\20"+
    "\1\21\1\22\1\23\2\24\1\4\2\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\25\1\33\1\25\1\34\1\25"+
    "\1\35\1\25\1\36\1\37\1\40\1\25\1\41\2\42"+
    "\1\43\3\42\1\44\17\42\1\45\23\42\2\46\1\47"+
    "\2\50\5\46\1\51\13\46\1\52\23\46\53\0\2\5"+
    "\1\0\1\5\70\0\1\53\35\0\1\54\4\0\1\55"+
    "\46\0\1\56\54\0\1\11\6\0\1\57\43\0\1\60"+
    "\5\0\1\57\44\0\1\60\4\0\1\57\51\0\1\57"+
    "\45\0\1\61\1\0\1\21\51\0\1\62\5\0\22\62"+
    "\22\0\1\25\2\0\2\25\1\0\22\25\22\0\1\25"+
    "\2\0\2\25\1\0\16\25\1\63\3\25\22\0\1\25"+
    "\2\0\2\25\1\0\14\25\1\64\5\25\22\0\1\25"+
    "\2\0\2\25\1\0\5\25\1\65\14\25\22\0\1\25"+
    "\2\0\2\25\1\0\12\25\1\66\7\25\22\0\1\25"+
    "\2\0\2\25\1\0\1\25\1\67\6\25\1\70\10\25"+
    "\1\71\22\0\1\25\2\0\2\25\1\0\13\25\1\72"+
    "\6\25\22\0\1\25\2\0\2\25\1\0\14\25\1\73"+
    "\5\25\22\0\1\25\2\0\2\25\1\0\21\25\1\74"+
    "\22\0\1\25\2\0\2\25\1\0\5\25\1\75\14\25"+
    "\22\0\1\25\2\0\2\25\1\0\20\25\1\76\1\25"+
    "\22\0\1\25\2\0\2\25\1\0\16\25\1\77\3\25"+
    "\52\0\1\56\2\42\1\0\3\42\1\0\17\42\1\0"+
    "\23\42\2\100\3\0\1\100\1\101\17\100\1\102\13\100"+
    "\1\103\2\100\1\104\1\100\1\105\2\100\12\0\1\106"+
    "\37\0\2\107\3\0\5\107\1\110\13\107\1\110\13\107"+
    "\1\110\2\107\1\110\1\107\1\110\2\107\2\54\1\0"+
    "\47\54\14\55\1\111\35\55\21\0\1\112\51\0\1\113"+
    "\5\0\22\113\22\0\1\25\2\0\2\25\1\0\5\25"+
    "\1\114\14\25\22\0\1\25\2\0\2\25\1\0\13\25"+
    "\1\115\6\25\22\0\1\25\2\0\2\25\1\0\3\25"+
    "\1\116\16\25\22\0\1\25\2\0\2\25\1\0\17\25"+
    "\1\117\2\25\22\0\1\25\2\0\2\25\1\0\12\25"+
    "\1\120\7\25\22\0\1\25\2\0\2\25\1\0\13\25"+
    "\1\121\6\25\22\0\1\25\2\0\2\25\1\0\13\25"+
    "\1\122\6\25\22\0\1\25\2\0\2\25\1\0\15\25"+
    "\1\123\4\25\22\0\1\25\2\0\2\25\1\0\14\25"+
    "\1\124\5\25\22\0\1\25\2\0\2\25\1\0\20\25"+
    "\1\72\1\25\22\0\1\25\2\0\2\25\1\0\20\25"+
    "\1\125\1\25\22\0\1\25\2\0\2\25\1\0\1\25"+
    "\1\126\20\25\22\0\1\25\2\0\2\25\1\0\21\25"+
    "\1\127\1\0\7\55\1\130\4\55\1\111\35\55\21\0"+
    "\1\131\3\0\1\132\6\0\1\132\36\0\1\133\5\0"+
    "\22\133\22\0\1\25\2\0\2\25\1\0\1\25\1\134"+
    "\20\25\22\0\1\25\2\0\2\25\1\0\4\25\1\135"+
    "\13\25\1\136\1\25\22\0\1\25\2\0\2\25\1\0"+
    "\12\25\1\137\7\25\22\0\1\25\2\0\2\25\1\0"+
    "\5\25\1\140\14\25\22\0\1\25\2\0\2\25\1\0"+
    "\17\25\1\127\2\25\22\0\1\25\2\0\2\25\1\0"+
    "\10\25\1\141\11\25\22\0\1\25\2\0\2\25\1\0"+
    "\3\25\1\142\16\25\22\0\1\25\2\0\2\25\1\0"+
    "\21\25\1\143\22\0\1\25\2\0\2\25\1\0\15\25"+
    "\1\140\4\25\22\0\1\25\2\0\2\25\1\0\21\25"+
    "\1\144\22\0\1\25\2\0\2\25\1\0\16\25\1\143"+
    "\3\25\22\0\1\25\2\0\2\25\1\0\5\25\1\145"+
    "\14\25\22\0\1\146\3\0\1\132\6\0\1\132\32\0"+
    "\2\147\2\0\1\150\51\0\1\151\5\0\22\151\22\0"+
    "\1\25\2\0\2\25\1\0\11\25\1\140\10\25\22\0"+
    "\1\25\2\0\2\25\1\0\10\25\1\142\11\25\22\0"+
    "\1\25\2\0\2\25\1\0\10\25\1\152\11\25\22\0"+
    "\1\25\2\0\2\25\1\0\1\25\1\153\20\25\22\0"+
    "\1\25\2\0\2\25\1\0\17\25\1\154\2\25\22\0"+
    "\1\25\2\0\2\25\1\0\20\25\1\155\1\25\22\0"+
    "\1\25\2\0\2\25\1\0\20\25\1\140\1\25\22\0"+
    "\1\25\2\0\2\25\1\0\16\25\1\156\3\25\22\0"+
    "\1\157\3\0\1\132\6\0\1\132\36\0\1\150\51\0"+
    "\1\160\5\0\22\160\22\0\1\25\2\0\2\25\1\0"+
    "\13\25\1\161\6\25\22\0\1\25\2\0\2\25\1\0"+
    "\16\25\1\117\3\25\22\0\1\25\2\0\2\25\1\0"+
    "\7\25\1\140\12\25\22\0\1\25\2\0\2\25\1\0"+
    "\10\25\1\162\11\25\22\0\1\25\2\0\2\25\1\0"+
    "\13\25\1\140\6\25\22\0\1\163\3\0\1\132\6\0"+
    "\1\132\36\0\1\164\5\0\22\164\22\0\1\25\2\0"+
    "\2\25\1\0\21\25\1\117\22\0\1\25\2\0\2\25"+
    "\1\0\14\25\1\156\5\25\22\0\1\165\3\0\1\132"+
    "\6\0\1\132\36\0\1\166\5\0\22\166\22\0\1\167"+
    "\3\0\1\132\6\0\1\132\36\0\1\170\5\0\22\170"+
    "\22\0\1\167\51\0\1\171\5\0\22\171\22\0\1\172"+
    "\5\0\22\172\22\0\1\173\5\0\22\173\22\0\1\174"+
    "\5\0\22\174\22\0\1\175\5\0\22\175\22\0\1\176"+
    "\5\0\22\176\22\0\1\177\5\0\22\177\22\0\1\200"+
    "\5\0\22\200\22\0\1\201\5\0\22\201\22\0\1\202"+
    "\5\0\22\202\22\0\1\203\5\0\22\203\22\0\1\204"+
    "\5\0\22\204\22\0\1\205\5\0\22\205\22\0\1\206"+
    "\5\0\22\206\22\0\1\207\5\0\22\207\22\0\1\210"+
    "\5\0\22\210\22\0\1\211\5\0\22\211\22\0\1\212"+
    "\5\0\22\212\22\0\1\213\5\0\22\213\22\0\1\214"+
    "\5\0\22\214\22\0\1\215\5\0\22\215\22\0\1\216"+
    "\5\0\22\216\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4746];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\1\11\1\1\1\11\1\1\2\11"+
    "\26\1\2\11\1\0\1\1\1\11\1\0\1\11\1\1"+
    "\1\11\2\1\3\11\17\1\10\11\20\1\1\11\1\1"+
    "\1\0\14\1\1\0\46\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /* User code - helper methods */
    private SymbolTable symbolTable = new SymbolTable();
    private ErrorHandler errorHandler = new ErrorHandler();
    private int commentsRemoved = 0;
    private java.util.List<Token> tokenList = new java.util.ArrayList<>();
    private java.util.Map<TokenType, Integer> tokenCounts = new java.util.LinkedHashMap<>();

    {
        for (TokenType t : TokenType.values()) {
            tokenCounts.put(t, 0);
        }
    }

    private Token makeToken(TokenType type, String lexeme) {
        Token t = new Token(type, lexeme, yyline + 1, yycolumn + 1);
        tokenList.add(t);
        tokenCounts.put(type, tokenCounts.getOrDefault(type, 0) + 1);
        return t;
    }

    public SymbolTable getSymbolTable() { return symbolTable; }
    public ErrorHandler getErrorHandler() { return errorHandler; }
    public int getCommentsRemoved() { return commentsRemoved; }
    public java.util.List<Token> getTokenList() { return tokenList; }
    public java.util.Map<TokenType, Integer> getTokenCounts() { return tokenCounts; }

    /* StringBuilder for string/char literal building */
    private StringBuilder stringBuffer = new StringBuilder();
    private int stringStartLine;
    private int stringStartCol;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case STRING_STATE: {
              errorHandler.reportUnterminatedString(stringStartLine, stringStartCol,
                  stringBuffer.toString());
              makeToken(TokenType.ERROR, stringBuffer.toString());
              yybegin(YYINITIAL);
              return makeToken(TokenType.EOF, "");
            }  // fall though
            case 143: break;
            case CHAR_STATE: {
              errorHandler.reportUnterminatedChar(stringStartLine, stringStartCol,
                  stringBuffer.toString());
              makeToken(TokenType.ERROR, stringBuffer.toString());
              yybegin(YYINITIAL);
              return makeToken(TokenType.EOF, "");
            }  // fall though
            case 144: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errorHandler.reportInvalidCharacter(yyline + 1, yycolumn + 1, yytext());
          makeToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 35: break;
          case 2:
            { /* skip */
            }
          // fall through
          case 36: break;
          case 3:
            { makeToken(TokenType.LOGICAL_OP, yytext());
            }
          // fall through
          case 37: break;
          case 4:
            { stringBuffer.setLength(0);
          stringBuffer.append('"');
          stringStartLine = yyline + 1;
          stringStartCol = yycolumn + 1;
          yybegin(STRING_STATE);
            }
          // fall through
          case 38: break;
          case 5:
            { makeToken(TokenType.ARITHMETIC_OP, yytext());
            }
          // fall through
          case 39: break;
          case 6:
            { stringBuffer.setLength(0);
          stringBuffer.append('\'');
          stringStartLine = yyline + 1;
          stringStartCol = yycolumn + 1;
          yybegin(CHAR_STATE);
            }
          // fall through
          case 40: break;
          case 7:
            { makeToken(TokenType.PUNCTUATOR, yytext());
            }
          // fall through
          case 41: break;
          case 8:
            { makeToken(TokenType.INTEGER_LITERAL, yytext());
            }
          // fall through
          case 42: break;
          case 9:
            { makeToken(TokenType.RELATIONAL_OP, yytext());
            }
          // fall through
          case 43: break;
          case 10:
            { makeToken(TokenType.ASSIGNMENT_OP, yytext());
            }
          // fall through
          case 44: break;
          case 11:
            { makeToken(TokenType.IDENTIFIER, yytext());
          symbolTable.addIdentifier(yytext(), yyline + 1, yycolumn + 1);
            }
          // fall through
          case 45: break;
          case 12:
            { errorHandler.reportInvalidIdentifier(yyline + 1, yycolumn + 1, yytext(),
            "Identifier must start with an uppercase letter (A-Z)");
          makeToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 46: break;
          case 13:
            { stringBuffer.append(yytext());
            }
          // fall through
          case 47: break;
          case 14:
            { errorHandler.reportUnterminatedString(stringStartLine, stringStartCol,
                  stringBuffer.toString());
              makeToken(TokenType.ERROR, stringBuffer.toString());
              yybegin(YYINITIAL);
            }
          // fall through
          case 48: break;
          case 15:
            { stringBuffer.append('"');
          makeToken(TokenType.STRING_LITERAL, stringBuffer.toString());
          yybegin(YYINITIAL);
            }
          // fall through
          case 49: break;
          case 16:
            { errorHandler.reportUnterminatedChar(stringStartLine, stringStartCol,
                  stringBuffer.toString());
              makeToken(TokenType.ERROR, stringBuffer.toString());
              yybegin(YYINITIAL);
            }
          // fall through
          case 50: break;
          case 17:
            { stringBuffer.append('\'');
          errorHandler.reportMalformedLiteral(stringStartLine, stringStartCol,
              stringBuffer.toString(), "Empty character literal");
          makeToken(TokenType.ERROR, stringBuffer.toString());
          yybegin(YYINITIAL);
            }
          // fall through
          case 51: break;
          case 18:
            { makeToken(TokenType.SINGLE_LINE_COMMENT, yytext()); commentsRemoved++;
            }
          // fall through
          case 52: break;
          case 19:
            { errorHandler.reportUnclosedComment(yyline + 1, yycolumn + 1, yytext());
          makeToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 53: break;
          case 20:
            { makeToken(TokenType.INC_DEC_OP, yytext());
            }
          // fall through
          case 54: break;
          case 21:
            { errorHandler.reportMalformedLiteral(yyline + 1, yycolumn + 1, yytext(),
            "Floating-point literal must have digits after decimal point");
          makeToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 55: break;
          case 22:
            { stringBuffer.append(yytext());
              errorHandler.reportInvalidEscape(stringStartLine, stringStartCol,
                  yytext(), "Invalid escape sequence '" + yytext() + "'");
            }
          // fall through
          case 56: break;
          case 23:
            { stringBuffer.append("\\\"");
            }
          // fall through
          case 57: break;
          case 24:
            { stringBuffer.append("\\\\");
            }
          // fall through
          case 58: break;
          case 25:
            { stringBuffer.append("\\n");
            }
          // fall through
          case 59: break;
          case 26:
            { stringBuffer.append("\\r");
            }
          // fall through
          case 60: break;
          case 27:
            { stringBuffer.append("\\t");
            }
          // fall through
          case 61: break;
          case 28:
            { stringBuffer.append(yytext());
          makeToken(TokenType.CHAR_LITERAL, stringBuffer.toString());
          yybegin(YYINITIAL);
            }
          // fall through
          case 62: break;
          case 29:
            { stringBuffer.append(yytext());
              errorHandler.reportInvalidEscape(stringStartLine, stringStartCol,
                  yytext(), "Invalid escape sequence '" + yytext() + "'");
              /* try to consume closing quote */
            }
          // fall through
          case 63: break;
          case 30:
            { makeToken(TokenType.FLOAT_LITERAL, yytext());
            }
          // fall through
          case 64: break;
          case 31:
            { makeToken(TokenType.MULTI_LINE_COMMENT, yytext()); commentsRemoved++;
            }
          // fall through
          case 65: break;
          case 32:
            { makeToken(TokenType.KEYWORD, yytext());
            }
          // fall through
          case 66: break;
          case 33:
            { makeToken(TokenType.BOOLEAN_LITERAL, yytext());
            }
          // fall through
          case 67: break;
          case 34:
            { errorHandler.reportMalformedLiteral(yyline + 1, yycolumn + 1, yytext(),
            "Floating-point literal has more than 6 decimal digits");
          makeToken(TokenType.ERROR, yytext());
            }
          // fall through
          case 68: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
